preparing_apply_kernel_module_kernel_modules:
  - overlay
  - br_netfilter

preparing_apply_kernel_module_kernel_params:
  - name: net.bridge.bridge-nf-call-iptables
    value: 1
  - name: net.bridge.bridge-nf-call-ip6tables
    value: 1
  - name: net.ipv4.ip_forward
    value: 1
