all:
  children:
    control_planes:
      hosts:
        control0:
          ansible_host: 192.168.0.129
    worker_nodes:
      hosts:
        worker0:
          ansible_host: 192.168.0.131
  vars:
    # Ansible
    ansible_user: ansible
    ansible_private_key_file: ./decrypted_key
    # K8s
    cluster_name: cffnpwr-home-k8s-cluster
    k8s_version: 1.31
    cri: containerd
    cni: cilium
    pod_network_cidr: 10.0.0.0/8
    apiserver_endpoint: apiserver-endpoint
    vip: 192.168.0.128
    kube_vip_version: 0.8.3
