- name: Configure /etc/hosts
  block:
    - name: Add the VIP and the API server endpoint to /etc/hosts
      become: true
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: ^{{ vip }}
        line: "{{ vip }} {{ apiserver_endpoint }}"

  rescue:
    - name: Copy /etc/hosts to /tmp/hosts
      ansible.builtin.copy:
        remote_src: true
        src: /etc/hosts
        dest: /tmp/hosts
        mode: "644"

    - name: Add the VIP and the API server endpoint to /tmp/hosts
      ansible.builtin.lineinfile:
        path: /tmp/hosts
        regexp: ^{{ vip }}
        line: "{{ vip }} {{ apiserver_endpoint }}"

    - name: Copy /tmp/hosts to /etc/hosts
      changed_when: false
      become: true
      ansible.builtin.command: cp /tmp/hosts /etc/hosts

    - name: Remove /tmp/hosts
      changed_when: false
      ansible.builtin.file:
        path: /tmp/hosts
        state: absent
