all:
  vars:
    # Ansible
    ansible_user: ansible
    ansible_private_key_file: ./decrypted_key
    # K8s
    cluster_name: k8s-cluster
    k8s_version: 1.31
    cri: containerd
    cni: cilium
    pod_network_cidr: 10.0.0.0/8
    apiserver_endpoint: apiserver-endpoint
    vip: 10.255.255.100
    kube_vip_version: 0.8.3
