- name: Check Swap State
  become: true
  changed_when: false
  check_mode: false
  ansible.builtin.command: swapon -v
  register: swap_state

- name: Swap Off
  become: true
  changed_when: false
  check_mode: false
  when: swap_state.stdout != ""
  ansible.builtin.command: swapoff -a

- name: Check /etc/fstab
  changed_when: false
  check_mode: false
  ignore_errors: true
  ansible.builtin.shell:
    cmd: |-
      set -o pipefail
      grep -v "\s*#" /etc/fstab | awk '{print $3}' | grep swap -c
    executable: /bin/bash
  register: swap_in_fstab

- name: Remove Swap from /etc/fstab
  become: true
  changed_when: false
  check_mode: false
  when: swap_in_fstab.stdout != "0"
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: (.+\s+swap\s+.*)
    replace: '# \1'
