FROM {{ item.image }}

ARG UID=1000
ARG GID=1000
ARG USER="ansible"
ARG PASSWORD="ac7nwZ1rrQ1DRea/R0VE93enSmlzJmrZn380d9X8NBmypybszREdk9Uifj6N5k9y"
ARG PUB_KEY="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN+1S+13EGhVV9U0RoQW4zQm/fSSJOFlSmU7MhB3ZZSc for ansible"

RUN apt-get -qq update; \
  apt-get -qq install -y --no-install-recommends kmod sudo openssh-server; \
  apt-get -qq clean; \
  rm -rf /var/lib/apt/lists/*; \
  groupadd -r --gid ${GID} ${USER}; \
  useradd -m -r --uid ${UID} --gid ${GID} -G sudo ${USER}; \
  echo ${USER}:${PASSWORD} | chpasswd; \
  mkdir /var/run/sshd; \
  ssh-keygen -A; \
  mkdir -p /home/${USER}/.ssh; \
  touch /home/${USER}/.ssh/authorized_keys; \
  echo ${PUB_KEY} >> /home/${USER}/.ssh/authorized_keys

CMD ["/usr/sbin/sshd", "-D"]
