services:
  iac:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - ..:/workspace
    networks:
      default:
      internal:
        ipv4_address: 10.255.255.254
    tty: true
    init: true
    stdin_open: true

  controle_plane0:
    build:
      context: .
      dockerfile: ./Dockerfile.node
    networks:
      default:
      internal:
        ipv4_address: 10.255.255.10

  worker_node0:
    build:
      context: .
      dockerfile: ./Dockerfile.node
    networks:
      default:
      internal:
        ipv4_address: 10.255.255.20

networks:
  internal:
    internal: true
    ipam:
      config:
        - subnet: 10.255.255.0/24
