- name: Add Repository Key
  become: true
  ansible.builtin.get_url:
    url: "https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/Release.key"
    dest: /etc/apt/keyrings/kubernetes.asc
    mode: "644"
    force: true

- name: Add Repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes.asc] https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/ /"
    filename: kubernetes
    state: present

- name: Install Kubetools
  become: true
  ansible.builtin.apt:
    update_cache: true
    install_recommends: false
    allow_change_held_packages: true
    name: "{{ install_kubetools_apt_packages | product([k8s_version ~ '.*']) | map('join', '=') | list }}"
