name: Test
on:
  pull_request:
    branches:
      - main
      - release/*
    paths:
      - molecule/**
      - playbooks/**
      - .github/workflows/test.yaml

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup vagrant and libvirt
        run: |
          curl -sSfL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get -qq update
          sudo apt-get -qq install -y --no-install-recommends bridge-utils clang dnsmasq kmod libguestfs-tools libvirt-clients libvirt-daemon-system libvirt-dev pkg-config qemu-kvm qemu-utils vagrant virt-manager
          sudo usermod -aG libvirt,kvm ${USER}
          vagrant plugin install vagrant-libvirt

      - name: Setup uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Set uv path
        run: echo "UV_PATH=$(which uv)" >> $GITHUB_ENV

      - name: uv sync
        run: uv sync

      - name: Set Vault Password
        env:
          VAULT_PASS: ${{ secrets.VAULT_PASS }}
        run: echo "${VAULT_PASS}" > ${PWD}/vault_pass

      - name: Set encrypted private key
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: echo "${PRIVATE_KEY}" > ${PWD}/encrypted_key

      - name: molecule test
        env:
          ANSIBLE_VAULT_PASSWORD_FILE: ${PWD}/vault_pass
        run: sudo -s -u ${USER} ${{ env.UV_PATH }} run molecule test
