- name: Collect Gather Facts
  ansible.builtin.gather_facts:
    gather_subset:
      - min

- name: Install Kubetools for apt
  ansible.builtin.import_tasks: ./apt.yaml
  when: ansible_facts.pkg_mgr == "apt"
